spring.application.name=fitcare
server.port=${PORT:8081}

# Free MySQL
spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/sql12830875?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=sql12830875
spring.datasource.password=VfesTlC8bd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=3

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

fitcare.jwt.secret=${JWT_SECRET}
fitcare.jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.fitcare=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR