services:
  - type: web
    name: ai-mock-interview
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://switchyard.proxy.rlwy.net:22701/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        sync: false
      - key: APP_JWT_EXPIRATION
        value: 86400000
      - key: GROQ_API_KEY
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update